export const allProducts = [
  {
    id: 1,
    name: 'KAOS BASIC COTTON KENARI - DUSTY ROSE',
    description:
      'Cotton Combed 30s, nyaman dan cocok untuk berbagai aktivitas.',
    image: '/cardImage/Rectangle 40352.png',
    price: 150000,
    stock: 20,
    sku: '0219AKD192',
    isActive: true,
    Url: 'https://example.com/product/1',
  },
  {
    id: 2,
    name: 'HOODIE OVERSIZED - BLACK',
    description: 'Hoodie oversized dengan bahan fleece yang hangat.',
    image: '/cardImage/Rectangle 40352.png',
    price: 250000,
    stock: 10,
    sku: '0392HDB192',
    isActive: true,
    Url: 'https://example.com/product/2',
  },
  {
    id: 3,
    name: 'CELANA CHINO SLIM FIT - BEIGE',
    description: 'Celana chino slim fit dengan warna beige yang elegan.',
    image: '/cardImage/Rectangle 40352.png',
    price: 200000,
    stock: 15,
    sku: '0501CHB203',
    isActive: false,
    Url: 'https://example.com/product/3',
  },
  {
    id: 4,
    name: 'KEMEJA FLANEL - RED CHECKERED',
    description: 'Kemeja flanel motif kotak-kotak merah.',
    image: '/cardImage/Rectangle 40352.png',
    price: 180000,
    stock: 8,
    sku: '0820KFR204',
    isActive: true,
    Url: 'https://example.com/product/4',
  },
  {
    id: 5,
    name: 'TOPI SNAPBACK - WHITE',
    description: 'Topi snapback berwarna putih dengan desain modern.',
    image: '/cardImage/Rectangle 40352.png',
    price: 120000,
    stock: 30,
    sku: '0973TWB105',
    isActive: false,
    Url: 'https://example.com/product/5',
  },
];
